version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12.10-management
    container_name: rabbitmq-local-dev
    ports:
      - "15672:5672"
      - "25672:15672"
    expose:
      - "5672"
      - "15672"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pwd1234!
      - TZ=Asia/Seoul
    networks:
      - rabbit-q
    mem_limit: "256mb"
  producer:
    image: rabbitmq-producer:v1
    container_name: rabbitmq-local-producer
    build:
      context: ./producer
    ports:
      - "7071:7071"
    expose:
      - "7071"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    entrypoint: java -jar -Dspring.rabbitmq.host=rabbitmq -Dspring.rabbitmq.port=5672 producer-0.0.1-SNAPSHOT.jar
    networks:
      - rabbit-q
    mem_limit: "128mb"
    depends_on:
      - rabbitmq
  consumer:
    image: rabbitmq-consumer:v1
    container_name: rabbitmq-local-consumer
    build:
      context: ./consumer
    ports:
      - "9099:9099"
    expose:
      - "9099"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    entrypoint: java -jar -Dspring.rabbitmq.host=rabbitmq -Dspring.rabbitmq.port=5672 consumer-0.0.1-SNAPSHOT.jar
    networks:
      - rabbit-q
    mem_limit: "128mb"
    depends_on:
      - rabbitmq

networks:
  rabbit-q:
    driver: bridge